// Employee-facing Annual Evaluation view: tag each achievement to a criteria and/or goal,
// self-assess every category, declare "nothing to report" for criteria/goals with no
// achievements, submit for head review; the head may return it once for another round of edits
// (RETURNED_TO_EMPLOYEE re-opens the same editing controls) before their final submit-and-sign;
// once the head has submitted-and-signed, sign or refuse to sign (with a required rationale);
// once concluded, download the final report.
import { useState, useEffect } from 'react'
import { Card, Select, Table, Tag, Button, Modal, Form, Input, Checkbox, message, Descriptions, Alert, Empty, Space, Typography, Tooltip, Popconfirm } from 'antd'
import { CheckCircleOutlined, CloseCircleOutlined, DownloadOutlined, LockOutlined, EditOutlined, DeleteOutlined } from '@ant-design/icons'
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import { useTranslation } from 'react-i18next'
import { getAcademicYears, getMostRecentAcademicYear } from '../../api/academicYears'
import { getRankLabels, getAchievementModules } from '../../api/portfolio'
import {
  getMyEvaluation, updateEntryDesignation, updateSelfRank, updateGoalsSelfRank, markCriteriaNothingToReport,
  markGoalNothingToReport, submitEmployeeSelfAssessment, signAsEmployee, refuseToSign, downloadEvaluationPdf,
  updateCategoryEmployeeComments, updateGoalsEmployeeComments, updateCriterionEmployeeComments,
  updateEmployeeFinalSummary,
} from '../../api/annualEvaluations'
import {
  orderedCategoryResults, categoryColor, AchievementList, rankLabelText, GoalsSection, HeadCommentsBlock, EmployeeReflectionBlock,
  NextCycleGoalsSection, TeachingEvaluationsModal, EvaluationScoreSummary,
} from './evaluationDisplay'
import { AchievementModal, AchievementReportModal, useEditAchievementMutation, useDeleteAchievementMutation } from '../../components/AchievementModal'
import { useTerminology } from '../../TerminologyContext'

const { Text, Paragraph } = Typography

// Maps an achievement-module's stable code to the React component that renders its own
// button+recording interface -- adding a future module's frontend is just one new entry here.
const ACHIEVEMENT_MODULE_COMPONENTS = {
  TEACHING_EVALUATIONS: TeachingEvaluationsModal,
}

export default function AnnualEvaluationPage() {
  const { t } = useTranslation()
  const { defaultHeadTitleLabel, academicYearLabel } = useTerminology()
  const qc = useQueryClient()
  const [academicYearId, setAcademicYearId] = useState(null)
  const [refuseOpen, setRefuseOpen] = useState(false)
  const [rationale, setRationale] = useState('')
  const [signOpen, setSignOpen] = useState(false)
  const [signForm] = Form.useForm()

  // Changing an entry's Category is a two-step pick, not an immediate reassignment: selecting a
  // new category only stages it here (keyed by entryId) and prompts for a criterion within that
  // category; the actual designation update only fires once a criterion is chosen, with both the
  // new category and that criterion together.
  const [pendingCategoryByEntry, setPendingCategoryByEntry] = useState({})
  const [editingAchievement, setEditingAchievement] = useState(null)
  const [viewingAchievement, setViewingAchievement] = useState(null)

  const { data: academicYears = [] } = useQuery({ queryKey: ['academic-years'], queryFn: getAcademicYears })

  // Default to the most recent year instead of leaving the selector blank.
  useEffect(() => {
    if (!academicYearId && academicYears.length > 0) {
      setAcademicYearId(getMostRecentAcademicYear(academicYears).id)
    }
  }, [academicYearId, academicYears])

  const { data: evaluation, isLoading } = useQuery({
    queryKey: ['my-evaluation', academicYearId],
    queryFn: () => getMyEvaluation(academicYearId),
    enabled: !!academicYearId,
  })

  const { data: rankLabels = [] } = useQuery({
    queryKey: ['rank-labels', evaluation?.titleId],
    queryFn: () => getRankLabels(evaluation.titleId),
    enabled: !!evaluation?.titleId,
  })

  const { data: achievementModules = [] } = useQuery({
    queryKey: ['achievement-modules'],
    queryFn: getAchievementModules,
  })
  const achievementModuleLabel = (code) => achievementModules.find((m) => m.code === code)?.buttonLabel
    ?? achievementModules.find((m) => m.code === code)?.displayName ?? code

  const invalidate = () => qc.invalidateQueries({ queryKey: ['my-evaluation', academicYearId] })

  // Achievements generated by a criterion-assigned achievement tool (e.g. Teaching Evaluations)
  // have no measurement/Initiative at all -- this page is the only place they can ever be edited
  // or deleted, unlike ordinary achievements which are also reachable from the Strategy Tree.
  const editAchMut = useEditAchievementMutation([], null, null, () => { setEditingAchievement(null); invalidate() })
  const deleteAchMut = useDeleteAchievementMutation([], null, null, invalidate)

  const designationMut = useMutation({
    mutationFn: ({ entryId, categoryId, criteriaId, goalId }) =>
      updateEntryDesignation(evaluation.id, entryId, { categoryId, criteriaId, goalId }),
    onSuccess: invalidate,
    onError: (err) => message.error(err.response?.data?.message || t('annualEval.updateDesignationFailed')),
  })

  const selfRankMut = useMutation({
    mutationFn: ({ categoryId, rank }) => updateSelfRank(evaluation.id, categoryId, rank),
    onSuccess: invalidate,
    onError: (err) => message.error(err.response?.data?.message || t('annualEval.updateSelfRankFailed')),
  })

  const goalsSelfRankMut = useMutation({
    mutationFn: (rank) => updateGoalsSelfRank(evaluation.id, rank),
    onSuccess: invalidate,
    onError: (err) => message.error(err.response?.data?.message || t('annualEval.updateSelfRankFailed')),
  })

  const criteriaNtrMut = useMutation({
    mutationFn: ({ criteriaId, nothingToReport }) => markCriteriaNothingToReport(evaluation.id, criteriaId, nothingToReport),
    onSuccess: invalidate,
    onError: (err) => message.error(err.response?.data?.message || t('common.updateFailed')),
  })

  const goalNtrMut = useMutation({
    mutationFn: ({ goalId, nothingToReport }) => markGoalNothingToReport(evaluation.id, goalId, nothingToReport),
    onSuccess: invalidate,
    onError: (err) => message.error(err.response?.data?.message || t('common.updateFailed')),
  })

  const categoryEmployeeCommentsMut = useMutation({
    mutationFn: ({ categoryId, comments }) => updateCategoryEmployeeComments(evaluation.id, categoryId, comments),
    onSuccess: invalidate,
    onError: (err) => message.error(err.response?.data?.message || t('annualEval.saveCommentsFailed')),
  })

  const criteriaEmployeeCommentsMut = useMutation({
    mutationFn: ({ criteriaId, comments }) => updateCriterionEmployeeComments(evaluation.id, criteriaId, comments),
    onSuccess: invalidate,
    onError: (err) => message.error(err.response?.data?.message || t('annualEval.saveCommentsFailed')),
  })

  const goalsEmployeeCommentsMut = useMutation({
    mutationFn: (comments) => updateGoalsEmployeeComments(evaluation.id, comments),
    onSuccess: invalidate,
    onError: (err) => message.error(err.response?.data?.message || t('annualEval.saveCommentsFailed')),
  })

  const finalSummaryMut = useMutation({
    mutationFn: (comments) => updateEmployeeFinalSummary(evaluation.id, comments),
    onSuccess: invalidate,
    onError: (err) => message.error(err.response?.data?.message || t('annualEval.saveCommentsFailed')),
  })

  const submitMut = useMutation({
    mutationFn: () => submitEmployeeSelfAssessment(evaluation.id),
    onSuccess: () => { message.success(t('annualEval.selfAssessmentSubmitted')); invalidate() },
    onError: (err) => message.error(err.response?.data?.message || t('annualEval.submitFailed')),
  })

  const signMut = useMutation({
    mutationFn: (signatureName) => signAsEmployee(evaluation.id, signatureName),
    onSuccess: () => { message.success(t('annualEval.signedSuccess')); setSignOpen(false); signForm.resetFields(); invalidate() },
    onError: (err) => message.error(err.response?.data?.message || t('annualEval.signFailed')),
  })

  const refuseMut = useMutation({
    mutationFn: () => refuseToSign(evaluation.id, rationale),
    onSuccess: () => { message.success(t('annualEval.refusalRecorded')); setRefuseOpen(false); setRationale(''); invalidate() },
    onError: (err) => message.error(err.response?.data?.message || t('annualEval.refusalFailed')),
  })

  const handleDownload = async () => {
    try {
      const resp = await downloadEvaluationPdf(evaluation.id)
      const url = window.URL.createObjectURL(new Blob([resp.data]))
      const a = document.createElement('a')
      a.href = url
      a.download = `annual-evaluation-${evaluation.id}.pdf`
      a.click()
      window.URL.revokeObjectURL(url)
    } catch {
      message.error(t('annualEval.downloadFailed'))
    }
  }

  const isDraft = evaluation?.state === 'DRAFT'
  const isEmployeeSubmitted = evaluation?.state === 'EMPLOYEE_SUBMITTED'
  const isReturnedToEmployee = evaluation?.state === 'RETURNED_TO_EMPLOYEE'
  const isHeadSubmitted = evaluation?.state === 'HEAD_SUBMITTED'
  const isConcluded = evaluation?.state === 'CONCLUDED'
  const employeeHasActed = !!evaluation?.employeeSignedAt || evaluation?.employeeRefused
  // Editable both the very first time (DRAFT) and during the optional return-to-employee round.
  const canEmployeeEdit = isDraft || isReturnedToEmployee

  const criteriaOptionsFor = (categoryId) =>
    (evaluation?.criteriaResults ?? [])
      .filter((c) => c.categoryId === categoryId)
      .map((c) => ({ value: c.criteriaId, label: c.criteriaName }))

  const goalOptions = (evaluation?.goalResults ?? []).map((g) => ({ value: g.goalId, label: g.goalTitle }))

  const entryColumns = [
    {
      title: t('achievementLog.colAchievement'), dataIndex: 'achievementTitle', key: 'achievementTitle', width: 260,
      render: (title, row) => (
        <div style={{ display: 'flex', alignItems: 'center', gap: 4 }}>
          <Tooltip title={row.achievementDetails || t('tree.noAdditionalDetails')}>
            <span style={{ flex: 1, minWidth: 0, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap', cursor: 'pointer' }}
              onClick={() => setViewingAchievement(row)}>
              {title}
            </span>
          </Tooltip>
          {row.canEdit && (
            <Button type="text" size="small" icon={<EditOutlined />}
              onClick={() => setEditingAchievement(row)} style={{ color: '#6b7280', flexShrink: 0 }} />
          )}
          {row.canDelete && (
            <Popconfirm title={t('annualEval.deleteAchievementConfirmTitle')} description={t('annualEval.deleteAchievementConfirmDescription')}
              onConfirm={() => deleteAchMut.mutate(row.achievementId)}>
              <Button type="text" size="small" icon={<DeleteOutlined />} style={{ color: '#ef4444', flexShrink: 0 }} />
            </Popconfirm>
          )}
        </div>
      ),
    },
    {
      title: t('achievementLog.colCategory'), dataIndex: 'categoryId', key: 'categoryId', width: 180,
      render: (categoryId, row) => (canEmployeeEdit && !row.createdByModuleCode) ? (
        <Select
          style={{ width: '100%' }} value={pendingCategoryByEntry[row.entryId] ?? categoryId} placeholder={t('achievementModal.selectCategoryPlaceholder')}
          options={(evaluation.categoryResults ?? []).map((c) => ({ value: c.categoryId, label: c.categoryName }))}
          onChange={(value) => {
            // Staged only -- criteria must belong to the category it's tagged under, so switching
            // categories can't reassign the criterion (or clear it) on its own. Nothing is saved
            // until a criterion within this new category is chosen below.
            setPendingCategoryByEntry((prev) => ({ ...prev, [row.entryId]: value }))
            message.info(t('annualEval.selectCriterionInNewCategory'))
          }}
        />
      ) : (
        <Space size={4}>
          {evaluation.categoryResults.find((c) => c.categoryId === categoryId)?.categoryName ?? '—'}
          {row.createdByModuleCode && (
            <Tooltip title={t('achievementModal.categoryFixedByTool')}>
              <LockOutlined style={{ color: '#9ca3af', fontSize: 12 }} />
            </Tooltip>
          )}
        </Space>
      ),
    },
    {
      title: t('achievementModal.criteriaLabel'), dataIndex: 'criteriaId', key: 'criteriaId', width: 220,
      render: (criteriaId, row) => (canEmployeeEdit && !row.createdByModuleCode) ? (() => {
        const pendingCategoryId = pendingCategoryByEntry[row.entryId]
        const effectiveCategoryId = pendingCategoryId ?? row.categoryId
        return (
          <Select
            style={{ width: '100%' }} value={pendingCategoryId ? undefined : criteriaId}
            placeholder={pendingCategoryId ? t('annualEval.selectCriteriaInNewCategory') : t('achievementModal.selectCriteriaPlaceholder')}
            disabled={!effectiveCategoryId}
            options={criteriaOptionsFor(effectiveCategoryId)}
            onChange={(value) => {
              designationMut.mutate({ entryId: row.entryId, categoryId: effectiveCategoryId, criteriaId: value, goalId: row.goalId })
              setPendingCategoryByEntry((prev) => {
                const next = { ...prev }
                delete next[row.entryId]
                return next
              })
            }}
          />
        )
      })() : (
        <Space size={4}>
          {evaluation.criteriaResults.find((c) => c.criteriaId === criteriaId)?.criteriaName ?? <Tag color="red">{t('annualEval.notTagged')}</Tag>}
          {row.createdByModuleCode && (
            <Tooltip title={t('achievementModal.categoryFixedByTool')}>
              <LockOutlined style={{ color: '#9ca3af', fontSize: 12 }} />
            </Tooltip>
          )}
        </Space>
      ),
    },
    {
      title: t('annualEval.goalOptionalLabel'), dataIndex: 'goalId', key: 'goalId', width: 220,
      render: (goalId, row) => canEmployeeEdit ? (
        <Select
          style={{ width: '100%' }} value={goalId} placeholder={t('achievementModal.linkToGoalPlaceholder')} allowClear
          options={goalOptions}
          onChange={(value) => designationMut.mutate({ entryId: row.entryId, categoryId: row.categoryId, criteriaId: row.criteriaId, goalId: value })}
        />
      ) : (evaluation.goalResults?.find((g) => g.goalId === goalId)?.goalTitle ?? '—'),
    },
  ]

  const entriesFor = (criteriaId) => (evaluation?.entries ?? []).filter((e) => e.criteriaId === criteriaId)
  const entriesForGoal = (goalId) => (evaluation?.entries ?? []).filter((e) => e.goalId === goalId)

  const uncategorizedEntries = (evaluation?.entries ?? []).filter(
    (e) => !e.categoryId || !(evaluation?.categoryResults ?? []).some((c) => c.categoryId === e.categoryId))

  const missingSelfRank = (evaluation?.categoryResults ?? []).some((c) => !c.employeeSelfRank)
  const missingGoalsSelfRank = (evaluation?.goalResults?.length ?? 0) > 0 && !evaluation?.goalsEmployeeSelfRank
  const missingCriteria = (evaluation?.entries ?? []).some((e) => !e.criteriaId)
  const uncoveredCriteria = (evaluation?.criteriaResults ?? []).some(
    (c) => !c.employeeNothingToReport && entriesFor(c.criteriaId).length === 0)
  const uncoveredGoals = (evaluation?.goalResults ?? []).some(
    (g) => !g.employeeNothingToReport && entriesForGoal(g.goalId).length === 0)
  const missingCategoryComments = (evaluation?.categoryResults ?? []).some((c) => !c.employeeComments?.trim())
  const missingGoalsComments = (evaluation?.goalResults?.length ?? 0) > 0 && !evaluation?.goalsEmployeeComments?.trim()
  const missingFinalSummary = !evaluation?.employeeFinalSummary?.trim()
  const criteriaMissingMandatoryModule = (evaluation?.criteriaResults ?? []).filter((c) =>
    Object.entries(c.achievementModuleMandatory ?? {}).some(([code, mandatory]) =>
      mandatory && !entriesFor(c.criteriaId).some((e) => e.createdByModuleCode === code)))
  const missingMandatoryModule = criteriaMissingMandatoryModule.length > 0
  const canSubmit = !missingSelfRank && !missingGoalsSelfRank && !missingCriteria && !uncoveredCriteria
    && !uncoveredGoals && !missingCategoryComments && !missingGoalsComments && !missingFinalSummary
    && !missingMandatoryModule

  const missingItems = [
    missingSelfRank && t('annualEval.missingSelfRank'),
    missingGoalsSelfRank && t('annualEval.missingGoalsSelfRank'),
    missingCriteria && t('annualEval.missingCriteria'),
    uncoveredCriteria && t('annualEval.uncoveredCriteria'),
    uncoveredGoals && t('annualEval.uncoveredGoals'),
    missingCategoryComments && t('annualEval.missingCategoryComments'),
    missingGoalsComments && t('annualEval.missingGoalsComments'),
    missingFinalSummary && t('annualEval.missingFinalSummary'),
    missingMandatoryModule && t('annualEval.missingMandatoryModule', { criteria: criteriaMissingMandatoryModule.map((c) => c.criteriaName).join(', ') }),
  ].filter(Boolean)

  const handleSubmitClick = () => {
    if (missingItems.length > 0) {
      Modal.warning({
        title: t('annualEval.notReadyToSubmitTitle'),
        content: (
          <ul style={{ paddingLeft: 18, margin: 0 }}>
            {missingItems.map((item) => <li key={item}>{item}</li>)}
          </ul>
        ),
      })
      return
    }
    submitMut.mutate()
  }

  return (
    <div style={{ padding: 24 }}>
      <Card>
        <h1>{t('annualEval.title')}</h1>
        <Paragraph type="secondary">
          {t('annualEval.intro', { yearLabel: academicYearLabel.toLowerCase() })}
        </Paragraph>

        <Select
          style={{ width: 220, marginBottom: 24 }} placeholder={academicYearLabel} value={academicYearId}
          onChange={setAcademicYearId} options={academicYears.map((y) => ({ value: y.id, label: y.name }))}
        />

        {!academicYearId ? (
          <Empty description={t('annualEval.selectYearToView', { yearLabel: academicYearLabel })} />
        ) : isLoading || !evaluation ? null : (
          <>
            <Descriptions column={2} style={{ marginBottom: 16 }}>
              <Descriptions.Item label={evaluation.headTitle ?? defaultHeadTitleLabel}>{evaluation.headName}</Descriptions.Item>
              <Descriptions.Item label={t('common.status')}><Tag>{evaluation.state}</Tag></Descriptions.Item>
            </Descriptions>

            <EvaluationScoreSummary evaluation={evaluation} rankLabels={rankLabels} />

            <Card size="small" title={t('annualEval.evaluationDetailsTitle')} style={{ marginBottom: 16 }} />

            {(evaluation.entries ?? []).length === 0 && (
              <Empty description={t('annualEval.noneLoggedThisYear', { yearLabel: academicYearLabel.toLowerCase() })} style={{ marginBottom: 24 }} />
            )}

            {uncategorizedEntries.length > 0 && (
              <div style={{ marginBottom: 16 }}>
                <Text strong style={{ display: 'block', marginBottom: 4 }}>{t('annualEval.notYetCategorized')}</Text>
                <Table
                  dataSource={uncategorizedEntries} columns={entryColumns} rowKey="entryId"
                  pagination={false} size="small"
                />
              </div>
            )}

            {orderedCategoryResults(evaluation.categoryResults).map((cat, idx) => {
              const color = categoryColor(idx)
              const catCriteria = (evaluation.criteriaResults ?? []).filter((c) => c.categoryId === cat.categoryId)
              const catUnlinked = (evaluation.entries ?? []).filter((e) => e.categoryId === cat.categoryId && !e.criteriaId)
              return (
                <Card key={cat.categoryId} type="inner" title={cat.categoryName}
                  style={{ marginBottom: 16, borderTop: `4px solid ${color.accent}` }}
                  styles={{ header: { background: color.tint } }}
                  extra={
                    <Space>
                      <span>{t('annualEval.yourSelfRankLabel')}</span>
                      {canEmployeeEdit ? (
                        <Select style={{ width: 220 }} value={cat.employeeSelfRank} placeholder={t('annualEval.selectRankPlaceholder')}
                          options={[1, 2, 3, 4, 5].map((r) => ({ value: r, label: rankLabelText(rankLabels, r) }))}
                          onChange={(value) => selfRankMut.mutate({ categoryId: cat.categoryId, rank: value })} />
                      ) : (
                        <Tag color="magenta">{cat.employeeSelfRank ? rankLabelText(rankLabels, cat.employeeSelfRank) : '—'}</Tag>
                      )}
                      <Tag color="green">{t('annualEval.headRankLabel', { rank: cat.headCategoryRank ? rankLabelText(rankLabels, cat.headCategoryRank) : t('annualEval.notYetRated') })}</Tag>
                    </Space>
                  }
                >
                  {catCriteria.map((crit) => {
                    const critEntries = entriesFor(crit.criteriaId)
                    return (
                      <div key={crit.criteriaId} style={{ marginBottom: 16, paddingBottom: 16, borderBottom: '1px solid #e8eef6' }}>
                        <div style={{ marginBottom: 8 }}>
                          <Text strong>{t('annualEval.criterionLabel')} </Text>
                          <Text>{crit.criteriaName}</Text>
                          {canEmployeeEdit ? (
                            <Checkbox
                              checked={crit.employeeNothingToReport} disabled={critEntries.length > 0}
                              onChange={(e) => criteriaNtrMut.mutate({ criteriaId: crit.criteriaId, nothingToReport: e.target.checked })}
                              style={{ marginLeft: 12 }}
                            >
                              {t('annualEval.nothingToReport')}
                            </Checkbox>
                          ) : (
                            crit.employeeNothingToReport && <Tag color="gold" style={{ marginLeft: 8 }}>{t('annualEval.nothingToReport')}</Tag>
                          )}
                        </div>
                        <div style={{ marginBottom: 8 }}>
                          <Text strong style={{ display: 'block', marginBottom: 4 }}>{t('annualEval.criterionAchievementsLabel')}</Text>
                          {canEmployeeEdit ? (
                            <div style={{ background: color.tint, borderLeft: `3px solid ${color.accent}`, borderRadius: 4, padding: 10 }}>
                              <Text type="secondary" style={{ fontSize: 12, display: 'block', marginBottom: 4 }}>
                                {t('annualEval.changeMappingHint')}
                              </Text>
                              <Table
                                dataSource={critEntries} columns={entryColumns} rowKey="entryId"
                                pagination={false} size="small"
                                locale={{ emptyText: t('annualEval.noAchievementsTaggedYet') }}
                              />
                              {crit.achievementModuleCodes?.length > 0 && (
                                <Space style={{ marginTop: 8 }} wrap>
                                  {crit.achievementModuleCodes.map((code) => {
                                    const ModuleComponent = ACHIEVEMENT_MODULE_COMPONENTS[code]
                                    const maxAchievementsPerYear = crit.achievementModuleMaxPerYear?.[code]
                                    const countSoFar = critEntries.filter((e) => e.createdByModuleCode === code).length
                                    const limitReached = maxAchievementsPerYear != null && countSoFar >= maxAchievementsPerYear
                                    const mandatory = crit.achievementModuleMandatory?.[code]
                                    return ModuleComponent ? (
                                      <span key={code} style={{ display: 'inline-flex', alignItems: 'center', gap: 6 }}>
                                        <ModuleComponent
                                          evaluationId={evaluation.id} evaluation={evaluation}
                                          criteriaId={crit.criteriaId}
                                          buttonLabel={crit.achievementModuleDisplayNames?.[code] ?? achievementModuleLabel(code)}
                                          onAfterSave={invalidate}
                                          limitReached={limitReached}
                                          maxAchievementsPerYear={maxAchievementsPerYear}
                                        />
                                        {mandatory && (
                                          <Tag color={countSoFar > 0 ? 'green' : 'red'}>{countSoFar > 0 ? t('annualEval.requiredMet') : t('annualEval.requiredNotMet')}</Tag>
                                        )}
                                      </span>
                                    ) : null
                                  })}
                                </Space>
                              )}
                            </div>
                          ) : (
                            <AchievementList
                              entries={critEntries}
                              emptyText={crit.employeeNothingToReport ? t('annualEval.reportedNothingForCriteria') : t('annualEval.noAchievementsTaggedCriteria')}
                              color={color}
                            />
                          )}
                        </div>
                        <EmployeeReflectionBlock
                          comments={crit.employeeComments}
                          sectionName={crit.criteriaName}
                          color={color}
                          onSave={canEmployeeEdit ? (comments) => criteriaEmployeeCommentsMut.mutate({ criteriaId: crit.criteriaId, comments }) : undefined}
                        />
                        <div style={{ textAlign: 'right' }}>
                          <Tag color="green">
                            {t('annualEval.headRankLabel', { rank: crit.headRank ? rankLabelText(rankLabels, crit.headRank) : t('annualEval.notYetRated') })}
                          </Tag>
                        </div>
                      </div>
                    )
                  })}
                  {catUnlinked.length > 0 && (
                    <div>
                      <Text type="secondary" style={{ display: 'block', marginBottom: 4 }}>
                        <Tag color="gold" style={{ marginRight: 6 }}>{t('annualEval.needsCriteriaTag')}</Tag>{t('annualEval.notYetLinkedToCriteria')}
                      </Text>
                      <Table dataSource={catUnlinked} columns={entryColumns} rowKey="entryId" pagination={false} size="small" />
                    </div>
                  )}
                  <div style={{ marginTop: catCriteria.length > 0 ? 0 : 8 }}>
                    <EmployeeReflectionBlock
                      comments={cat.employeeComments}
                      sectionName={cat.categoryName}
                      required
                      onSave={canEmployeeEdit ? (comments) => categoryEmployeeCommentsMut.mutate({ categoryId: cat.categoryId, comments }) : undefined}
                    />
                    {!isDraft && (
                      <HeadCommentsBlock strengths={cat.headCommentsStrengths} improvements={cat.headCommentsImprovements} />
                    )}
                  </div>
                </Card>
              )
            })}

            <GoalsSection
              evaluation={evaluation} rankLabels={rankLabels} canEdit={false} showComments={!isDraft}
              onNothingToReportChange={canEmployeeEdit
                ? (goalId, nothingToReport) => goalNtrMut.mutate({ goalId, nothingToReport })
                : undefined}
              onSelfRankChange={canEmployeeEdit ? (rank) => goalsSelfRankMut.mutate(rank) : undefined}
              onEmployeeCommentsChange={canEmployeeEdit ? (comments) => goalsEmployeeCommentsMut.mutate(comments) : undefined}
            />

            <EmployeeReflectionBlock
              comments={evaluation.employeeFinalSummary}
              heading={t('annualEval.finalSummaryHeading')}
              required
              onSave={canEmployeeEdit ? (comments) => finalSummaryMut.mutate(comments) : undefined}
            />

            <NextCycleGoalsSection
              evaluationId={evaluation.id} evaluation={evaluation} canHeadEdit={false}
              canEmployeeReview={isReturnedToEmployee || (isHeadSubmitted && !employeeHasActed)}
              onAfterMutate={invalidate}
            />

            {isReturnedToEmployee && (
              <Alert type="warning" showIcon style={{ marginBottom: 12 }}
                message={t('annualEval.returnedForAnotherRound')} />
            )}

            {canEmployeeEdit && (
              <Button type="primary" loading={submitMut.isPending}
                onClick={handleSubmitClick}
                style={canSubmit
                  ? { background: '#13223a' }
                  : { background: '#f5f5f5', color: 'rgba(0, 0, 0, 0.45)', borderColor: '#d9d9d9' }}>
                {isReturnedToEmployee ? t('annualEval.resubmitForHeadReview') : t('annualEval.submitForHeadReview')}
              </Button>
            )}
            {canEmployeeEdit && !canSubmit && (
              <Alert type="info" showIcon style={{ marginTop: 12 }}
                message={t('annualEval.clickSubmitToSeeNeeded')} />
            )}

            {isEmployeeSubmitted && (
              <Alert type="info" showIcon message={t('annualEval.submittedWaitingHead')} />
            )}

            {(isHeadSubmitted || isConcluded) && (
              <>
                {evaluation.employeeRefused && (
                  <Alert type="warning" showIcon style={{ marginBottom: 12 }}
                    message={t('annualEval.youRefusedToSign')}
                    description={evaluation.employeeRefusalRationale} />
                )}
                {isHeadSubmitted && !employeeHasActed && (
                  <Space>
                    <Button type="primary" icon={<CheckCircleOutlined />}
                      onClick={() => setSignOpen(true)} style={{ background: '#13223a' }}>
                      {t('annualEval.signButton')}
                    </Button>
                    <Button danger icon={<CloseCircleOutlined />} onClick={() => setRefuseOpen(true)}>
                      {t('annualEval.refuseToSignButton')}
                    </Button>
                  </Space>
                )}
                {evaluation.employeeSignedAt && (
                  <Alert type="success" showIcon style={{ marginBottom: 12 }}
                    message={t('annualEval.signedByOn', { name: evaluation.employeeSignatureName, date: new Date(evaluation.employeeSignedAt).toLocaleDateString() })} />
                )}
                {employeeHasActed && !evaluation.headSignedAt && (
                  <Alert type="info" showIcon message={t('annualEval.waitingForHeadSignature')} />
                )}
                {isConcluded && (
                  <>
                    <Alert type="success" showIcon style={{ marginBottom: 12 }} message={t('annualEval.evaluationConcluded')} />
                    <Button icon={<DownloadOutlined />} onClick={handleDownload}>{t('annualEval.downloadReportButton')}</Button>
                  </>
                )}
              </>
            )}
          </>
        )}
      </Card>

      <Modal
        title={t('annualEval.refuseToSignTitle')} open={refuseOpen} onCancel={() => setRefuseOpen(false)}
        onOk={() => refuseMut.mutate()} confirmLoading={refuseMut.isPending}
        okButtonProps={{ danger: true, disabled: !rationale.trim() }}
      >
        <Text>{t('annualEval.refuseRationalePrompt')}</Text>
        <Input.TextArea rows={4} style={{ marginTop: 8 }} value={rationale} onChange={(e) => setRationale(e.target.value)} />
      </Modal>

      <Modal
        title={t('annualEval.signEvaluationTitle')} open={signOpen} onCancel={() => setSignOpen(false)} destroyOnClose
        onOk={() => signForm.submit()} confirmLoading={signMut.isPending} okText={t('annualEval.signButton')}
      >
        <Paragraph type="secondary">
          {t('annualEval.typeNameToSignHint')}
        </Paragraph>
        <Form form={signForm} layout="vertical" onFinish={(values) => signMut.mutate(values.signatureName)}>
          <Form.Item name="signatureName" label={t('annualEval.typeNameToSignLabel')} rules={[{ required: true, message: t('annualEval.typeNameToSignLabel') }]}>
            <Input placeholder={t('annualEval.yourFullNamePlaceholder')} />
          </Form.Item>
        </Form>
      </Modal>

      <AchievementModal
        open={!!editingAchievement} onClose={() => setEditingAchievement(null)}
        onSave={(values) => editAchMut.mutate({ achievementId: editingAchievement.achievementId, values })}
        loading={editAchMut.isPending}
        title={t('tree.editAchievementTitle')}
        assessmentPeriods={[]}
        academicYears={evaluation ? [{ id: evaluation.academicYearId, name: evaluation.academicYearName, closed: false }] : []}
        academicYearId={evaluation?.academicYearId}
        achievementId={editingAchievement?.achievementId}
        authorId={editingAchievement?.authorId}
        initialPeriodName={editingAchievement?.assessmentPeriodName}
        moduleLocked={!!editingAchievement?.createdByModuleCode}
        initialValues={editingAchievement ? {
          title: editingAchievement.achievementTitle,
          achievementTypeId: editingAchievement.achievementTypeId,
          customTypeName: editingAchievement.customTypeName,
          assessmentPeriodId: editingAchievement.assessmentPeriodId,
          details: editingAchievement.achievementDetails,
          privateNotes: editingAchievement.privateNotes,
        } : {}}
      />

      <AchievementReportModal
        achievement={viewingAchievement ? {
          id: viewingAchievement.achievementId,
          title: viewingAchievement.achievementTitle,
          details: viewingAchievement.achievementDetails,
          achievementTypeName: viewingAchievement.achievementTypeName,
          customTypeName: viewingAchievement.customTypeName,
          assessmentPeriodName: viewingAchievement.assessmentPeriodName,
          authorName: viewingAchievement.authorName,
          recordedAt: viewingAchievement.recordedAt,
          privateNotes: viewingAchievement.privateNotes,
        } : null}
        onClose={() => setViewingAchievement(null)}
      />
    </div>
  )
}
