// Achievement add/edit modal, its read-only "report" counterpart, and the mutation hooks that
// power both -- shared between the Strategy Tree (StrategyTree.jsx) and the Annual Evaluation
// page (AnnualEvaluationPage.jsx), since achievements generated by a criterion-assigned
// achievement tool (e.g. Teaching Evaluations) have no measurement/Initiative at all and so can
// ONLY ever be edited/viewed from the Annual Evaluation page, never the Strategy Tree.
import { useEffect } from 'react'
import { Form, Input, Modal, Rate, Select, Alert, Typography, message } from 'antd'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { useTranslation } from 'react-i18next'
import {
  getAchievements, getAchievementsAcrossYears, updateAchievement, deleteAchievement, getAchievementTypes,
} from '../api/strategies'
import {
  getMyCategories, getCategoriesForEmployee, getMyCycles, getCycleGoals,
  getEntryByAchievement, logAchievement as logAchievementWithEvaluation, upsertEntryForAchievement,
  getCriteria,
} from '../api/portfolio'
import { getMyEvaluation } from '../api/annualEvaluations'
import { useAuth } from '../auth/AuthContext'

const { Text } = Typography

// AI-generated achievement details (e.g. the Teaching Evaluation tool's "Generated AI Review")
// come back as one long run-on string -- the model doesn't reliably emit a real newline after
// every "Section:" header or before every "*" bullet, so a plain pre-wrap won't fix it. Force a
// line break at those spots so the structure the prompt asked for actually reads as structure.
const AI_DETAILS_SECTION_HEADERS = [
  'Generated AI Review', 'Instructor Reflection', 'Course Information', 'Strengths', 'Areas for Improvement',
]

export function formatAiDetails(text) {
  if (!text) return text
  const headerPattern = new RegExp(`(${AI_DETAILS_SECTION_HEADERS.join('|')}):\\s*`, 'g')
  return text
    .replace(headerPattern, '$1:\n')
    .replace(/\s*\*\s+/g, '\n* ')
    .replace(/\n{3,}/g, '\n\n')
    .trim()
}

// ─── AchievementModal (add & edit) ───────────────────────────────────────────

export function AchievementModal({
  open, onClose, onSave, loading, initialValues, assessmentPeriods, academicYears = [], title, initialPeriodName,
  academicYearId, achievementId, authorId, moduleLocked,
}) {
  const { t } = useTranslation()
  const [form] = Form.useForm()
  const { user } = useAuth()

  const { data: achievementTypes = [] } = useQuery({
    queryKey: ['achievement-types'],
    queryFn: getAchievementTypes,
    enabled: open,
  })

  // Editing someone else's achievement (Owner privilege) -- their categories/goals apply, not the editor's.
  const isSelf = !authorId || authorId === user?.userId

  const { data: categories = [], isError: categoriesError } = useQuery({
    queryKey: ['portfolio-categories-for-achievement', isSelf ? 'me' : authorId],
    queryFn: () => (isSelf ? getMyCategories() : getCategoriesForEmployee(authorId)),
    enabled: open,
    retry: false,
  })

  // The tree's own academic-year filter (`academicYearId`) is just a display filter and is often
  // unset -- it has nothing to do with which year this specific achievement belongs to. Resolve
  // the actual year from whichever assessment period the achievement is being recorded against
  // (periods and academic years share the same name, e.g. "2028-2029"), falling back to the tree
  // filter only if no period is known yet (the picker hasn't been touched).
  const watchedPeriodId = Form.useWatch('assessmentPeriodId', form)
  const selectedPeriodName = initialPeriodName ?? assessmentPeriods.find((p) => p.id === watchedPeriodId)?.name
  const effectiveAcademicYearId = selectedPeriodName
    ? academicYears.find((y) => y.name === selectedPeriodName)?.id
    : academicYearId

  const { data: myCycles = [] } = useQuery({
    queryKey: ['my-goal-cycles', effectiveAcademicYearId],
    queryFn: () => getMyCycles(effectiveAcademicYearId),
    enabled: open && isSelf && !!effectiveAcademicYearId,
  })
  const deployedCycle = myCycles.find((c) => c.state === 'DEPLOYED')
  const { data: myGoals = [] } = useQuery({
    queryKey: ['my-deployed-goals-for-achievement', deployedCycle?.id],
    queryFn: () => getCycleGoals(deployedCycle.id),
    enabled: open && isSelf && !!deployedCycle,
  })

  const { data: existingEntry } = useQuery({
    queryKey: ['portfolio-entry-for-achievement', achievementId],
    queryFn: () => getEntryByAchievement(achievementId),
    enabled: open && !!achievementId,
  })

  // Proactive UI mirror of the server-side gate in AchievementService.recordAchievement /
  // PortfolioEntryService -- once this cycle's evaluation has moved past DRAFT/RETURNED_TO_EMPLOYEE,
  // new achievements can no longer be added or re-tagged for it. Scoped to isSelf: editing someone
  // else's achievement (Owner privilege) has no convenient endpoint to check THEIR evaluation state
  // from here, so that case still falls back to the server's error toast on save.
  const { data: myEvaluation } = useQuery({
    queryKey: ['my-evaluation-for-achievement', effectiveAcademicYearId],
    queryFn: () => getMyEvaluation(effectiveAcademicYearId),
    enabled: open && isSelf && !!effectiveAcademicYearId,
  })
  const evaluationLocked = isSelf && !!myEvaluation
    && !['DRAFT', 'RETURNED_TO_EMPLOYEE'].includes(myEvaluation.state)

  // Criteria narrows to whichever category is currently selected in the form -- reload as it changes.
  const selectedCategoryId = Form.useWatch('categoryId', form)
  const { data: criteria = [] } = useQuery({
    queryKey: ['portfolio-criteria-for-achievement', selectedCategoryId],
    queryFn: () => getCriteria(selectedCategoryId),
    enabled: open && !!selectedCategoryId,
  })

  // "Other" reveals a free-text field for a custom type -- matched by name since achievementTypeId
  // is whatever id the admin's AchievementType table happens to assign it.
  const selectedAchievementTypeId = Form.useWatch('achievementTypeId', form)
  const otherAchievementType = achievementTypes.find((t) => t.systemCode === 'OTHER')
  const isOtherType = !!otherAchievementType && selectedAchievementTypeId === otherAchievementType.id

  useEffect(() => {
    if (!open) return
    form.setFieldsValue({
      ...initialValues,
      categoryId: existingEntry?.categoryId,
      criteriaId: existingEntry?.criteriaId,
      categoryRating: existingEntry?.categoryRating,
      goalId: existingEntry?.goalId,
      evidenceUrl: existingEntry?.evidenceUrl,
    })
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [open, existingEntry])

  const handleOk = async () => {
    try {
      const values = await form.validateFields()
      onSave(values)
    } catch {}
  }

  const noCategoriesConfigured = open && (categoriesError || categories.length === 0)

  return (
    <Modal title={title} open={open} onCancel={onClose} onOk={handleOk}
      confirmLoading={loading} okButtonProps={{ disabled: noCategoriesConfigured || evaluationLocked }} destroyOnClose>
      <Form form={form} layout="vertical" initialValues={initialValues}>
        <Form.Item name="title" label={t('common.title')} rules={[{ required: true }]}>
          <Input />
        </Form.Item>
        <Form.Item name="achievementTypeId" label={t('common.type')} rules={[{ required: true }]}>
          <Select placeholder={t('achievementModal.selectTypePlaceholder')}>
            {/* A deactivated type can't be picked for a new/different selection, but stays
                selectable here if it's the one this achievement already has -- so editing an old
                achievement never silently loses its type just because an admin retired it. */}
            {achievementTypes
              .filter((type) => type.active || type.id === selectedAchievementTypeId)
              .map((type) => (
                <Select.Option key={type.id} value={type.id}>{type.name}</Select.Option>
              ))}
          </Select>
        </Form.Item>
        {isOtherType && (
          <Form.Item name="customTypeName" label={t('achievementModal.customTypeLabel')} rules={[{ required: true, message: t('achievementModal.describeTypeRequired') }]}>
            <Input placeholder={t('achievementModal.describeTypePlaceholder')} />
          </Form.Item>
        )}
        {/* Assessment period is always fixed by context, never freely editable here -- every
            achievement must belong to a period, and it can't be changed once set (see
            AchievementService.updateAchievement, which now ignores assessmentPeriodId entirely on
            update). Hidden field carries the ID through validateFields; a required rule guards
            against a caller forgetting to resolve one before opening this modal. */}
        <Form.Item name="assessmentPeriodId" hidden rules={[{ required: true, message: t('achievementModal.periodRequired') }]}>
          <Input />
        </Form.Item>
        <Form.Item label={t('achievementModal.assessmentPeriodLabel')}>
          <span style={{
            display: 'inline-block', padding: '4px 10px', borderRadius: 6,
            background: '#eff6ff', color: '#1d4ed8', fontWeight: 600, fontSize: 13,
          }}>
            {initialPeriodName || '—'}
          </span>
        </Form.Item>
        <Form.Item name="details" label={t('achievementModal.detailsLabel')}
          extra={moduleLocked ? t('achievementModal.generatedByToolNotEditable') : undefined}>
          <Input.TextArea rows={2} disabled={moduleLocked} />
        </Form.Item>
        <Form.Item name="privateNotes" label={t('achievementModal.privateNotesLabel')} extra={t('achievementModal.onlyVisibleToYou')}>
          <Input.TextArea rows={2} />
        </Form.Item>

        {evaluationLocked && (
          <Alert type="warning" showIcon style={{ marginBottom: 16 }}
            message={t('achievementModal.evaluationLockedTitle')}
            description={t('achievementModal.evaluationLockedDescription')} />
        )}

        {noCategoriesConfigured ? (
          <Alert type="warning" showIcon style={{ marginBottom: 16 }}
            message={t('achievementModal.noCategoriesTitle')}
            description={t('achievementModal.noCategoriesDescription')} />
        ) : (
          <>
            <Form.Item name="categoryId" label={t('achievementModal.evaluationCategoryLabel')} rules={[{ required: true }]}
              extra={moduleLocked
                ? t('achievementModal.categoryFixedByTool')
                : t('achievementModal.categoryHint')}>
              <Select placeholder={t('achievementModal.selectCategoryPlaceholder')} disabled={moduleLocked}
                options={categories.map((c) => ({ value: c.id, label: c.categoryName }))}
                onChange={() => form.setFieldValue('criteriaId', undefined)} />
            </Form.Item>
            <Form.Item name="criteriaId" label={t('achievementModal.criteriaLabel')} rules={[{ required: true }]}
              extra={t('achievementModal.criteriaHint')}>
              <Select placeholder={selectedCategoryId ? t('achievementModal.selectCriteriaPlaceholder') : t('achievementModal.selectCategoryFirstPlaceholder')}
                disabled={!selectedCategoryId || moduleLocked}
                options={criteria.map((c) => ({ value: c.id, label: c.criteriaName }))} />
            </Form.Item>
          </>
        )}

        {isSelf && (
          <Form.Item name="goalId" label={t('achievementModal.relatedGoalLabel')}>
            <Select placeholder={t('achievementModal.linkToGoalPlaceholder')} allowClear
              options={myGoals.map((g) => ({ value: g.id, label: g.goalTitle }))} />
          </Form.Item>
        )}

        <Form.Item name="categoryRating" label={t('achievementModal.selfAssessmentRatingLabel')}>
          <Rate tooltips={[t('achievementModal.ratingPoor'), t('achievementModal.ratingFair'), t('achievementModal.ratingGood'), t('achievementModal.ratingVeryGood'), t('achievementModal.ratingExcellent')]} />
        </Form.Item>
        <Form.Item name="evidenceUrl" label={t('achievementModal.evidenceLinkLabel')} rules={[{ required: true, message: t('achievementModal.evidenceRequired') }]}
          extra={t('achievementModal.evidenceHint')}>
          <Input placeholder={t('achievementModal.evidenceUrlPlaceholder')} />
        </Form.Item>
        {!isSelf && (
          <Text type="secondary" style={{ fontSize: 12 }}>
            {t('achievementModal.goalLinkingAuthorOnly')}
          </Text>
        )}
      </Form>
    </Modal>
  )
}

// ─── shared achievement mutations ────────────────────────────────────────────
// Recording an achievement is identical whether triggered from a period group inside
// AchievementsPanel, an Initiative card's own quick-add button, the rail's search-and-log picker,
// or the Annual Evaluation page's own Edit/Add -- one hook per action, every call site, no
// duplicated request-shaping/invalidation logic. `measurements`/`initiativeId`/`strategyId` are
// all optional -- achievements with no measurement (module-generated) simply skip those
// invalidations, since Strategy Tree queries can never be caching data for them anyway.

export function useAddAchievementMutation(measurements, initiativeId, strategyId, onSuccessExtra) {
  const { t } = useTranslation()
  const qc = useQueryClient()
  return useMutation({
    mutationFn: (values) => logAchievementWithEvaluation({
      measurementId: measurements[0].id,
      achievementTitle: values.title,
      achievementTypeId: values.achievementTypeId,
      customTypeName: values.customTypeName,
      details: values.details,
      privateNotes: values.privateNotes,
      assessmentPeriodId: values.assessmentPeriodId,
      categoryId: values.categoryId,
      criteriaId: values.criteriaId,
      categoryRating: values.categoryRating,
      goalId: values.goalId,
      evidenceUrl: values.evidenceUrl,
    }),
    onSuccess: () => {
      message.success(t('achievementModal.recordedSuccess'))
      ;(measurements ?? []).forEach((m) => qc.invalidateQueries({ queryKey: ['achievements', m.id] }))
      qc.invalidateQueries({ queryKey: ['achievements-across-years', initiativeId] })
      if (strategyId) qc.invalidateQueries({ queryKey: ['recent-achievements', strategyId] })
      onSuccessExtra?.()
    },
    onError: (err) => message.error(err.response?.data?.message || t('achievementModal.recordFailed')),
  })
}

// Edit/delete are shared the same way -- used by AchievementsPanel's full list, the Initiative
// card's own quick-edit/delete icons, and the Annual Evaluation page's achievement column.
export function useEditAchievementMutation(measurements, initiativeId, strategyId, onSuccessExtra) {
  const { t } = useTranslation()
  const qc = useQueryClient()
  return useMutation({
    mutationFn: async ({ achievementId, values }) => {
      await updateAchievement(achievementId, {
        title: values.title,
        achievementTypeId: values.achievementTypeId,
        customTypeName: values.customTypeName,
        details: values.details,
        privateNotes: values.privateNotes,
        assessmentPeriodId: values.assessmentPeriodId,
      })
      await upsertEntryForAchievement(achievementId, {
        categoryId: values.categoryId,
        criteriaId: values.criteriaId,
        categoryRating: values.categoryRating,
        goalId: values.goalId,
        evidenceUrl: values.evidenceUrl,
      })
    },
    onSuccess: () => {
      message.success(t('achievementModal.updatedSuccess'))
      ;(measurements ?? []).forEach((m) => qc.invalidateQueries({ queryKey: ['achievements', m.id] }))
      qc.invalidateQueries({ queryKey: ['achievements-across-years', initiativeId] })
      if (strategyId) qc.invalidateQueries({ queryKey: ['recent-achievements', strategyId] })
      onSuccessExtra?.()
    },
    onError: (err) => message.error(err.response?.data?.message || t('common.updateFailed')),
  })
}

export function useDeleteAchievementMutation(measurements, initiativeId, strategyId, onSuccessExtra) {
  const { t } = useTranslation()
  const qc = useQueryClient()
  return useMutation({
    mutationFn: (id) => deleteAchievement(id),
    onSuccess: () => {
      message.success(t('achievementModal.deletedSuccess'))
      ;(measurements ?? []).forEach((m) => qc.invalidateQueries({ queryKey: ['achievements', m.id] }))
      qc.invalidateQueries({ queryKey: ['achievements-across-years', initiativeId] })
      if (strategyId) qc.invalidateQueries({ queryKey: ['recent-achievements', strategyId] })
      onSuccessExtra?.()
    },
    onError: (err) => message.error(err.response?.data?.message || t('common.deleteFailed')),
  })
}

// ─── AchievementReportModal ───────────────────────────────────────────────────
// Read-only "report" view of one achievement, shaped by who's looking -- the backend has already
// done the actual redaction before this ever renders: `achievement.privateNotes` only arrives
// non-null when the viewer IS the author (see AchievementService.toResponse), and
// `entry.goalTitle`/`goalId` only arrive non-null when the viewer is the author OR the chair
// assigned to review them for that academic year (see PortfolioEntryService.canViewGoalLink) --
// everyone else sees the same "—" a genuinely goal-less achievement would show, which is also
// what keeps this safe to reuse verbatim from the Strategy Tree, the employee's own Annual
// Evaluation page, and the chair's Team Evaluations review.

export function AchievementReportModal({ achievement, onClose }) {
  const { t } = useTranslation()
  const { data: entry, isLoading } = useQuery({
    queryKey: ['portfolio-entry-for-achievement', achievement?.id],
    queryFn: () => getEntryByAchievement(achievement.id),
    enabled: !!achievement,
  })

  return (
    <Modal title={t('achievementModal.reportTitle')} open={!!achievement} onCancel={onClose} footer={null} width={560} destroyOnClose>
      {!achievement ? null : isLoading ? (
        <div style={{ padding: 20, textAlign: 'center', color: '#9ca3af' }}>{t('tree.loadingEllipsis')}</div>
      ) : (
        <div className="ach-report">
          <div className="ach-report-row"><span className="k">{t('common.title')}</span><span className="v">{achievement.title}</span></div>
          <div className="ach-report-row"><span className="k">{t('common.type')}</span><span className="v">{achievement.customTypeName || achievement.achievementTypeName}</span></div>
          <div className="ach-report-row"><span className="k">{t('achievementModal.assessmentPeriodLabel')}</span><span className="v">{achievement.assessmentPeriodName || '—'}</span></div>
          <div className="ach-report-row"><span className="k">{t('achievementModal.recordedByLabel')}</span><span className="v">{achievement.authorName}</span></div>
          <div className="ach-report-row"><span className="k">{t('achievementModal.recordedAtLabel')}</span><span className="v">{new Date(achievement.recordedAt).toLocaleString()}</span></div>
          <div className="ach-report-row"><span className="k">{t('achievementModal.detailsLabel')}</span><span className="v" style={{ whiteSpace: 'pre-wrap' }}>{formatAiDetails(achievement.details) || '—'}</span></div>
          {/* Private Notes / Self-Assessment Rating / Evidence / Related Goal only ever arrive when
              the backend has decided this viewer is allowed to see them (see
              AchievementService.toResponse's isAuthor check and
              PortfolioEntryService.canViewSensitiveFields) -- for anyone else the row is hidden
              entirely, not shown blank, since a blank row reads as "empty" rather than "private". */}
          {achievement.privateNotes && (
            <div className="ach-report-row"><span className="k">{t('achievementModal.privateNotesLabel')}</span><span className="v">{achievement.privateNotes}</span></div>
          )}
          <div className="ach-report-row"><span className="k">{t('achievementModal.evaluationCategoryLabel')}</span><span className="v">{entry?.categoryName || '—'}</span></div>
          <div className="ach-report-row"><span className="k">{t('achievementModal.criteriaLabel')}</span><span className="v">{entry?.criteriaName || '—'}</span></div>
          {entry?.goalTitle && (
            <div className="ach-report-row"><span className="k">{t('achievementModal.relatedGoalReportLabel')}</span><span className="v">{entry.goalTitle}</span></div>
          )}
          {entry?.categoryRating && (
            <div className="ach-report-row">
              <span className="k">{t('achievementModal.selfAssessmentRatingLabel')}</span>
              <span className="v"><Rate disabled value={entry.categoryRating} style={{ fontSize: 14 }} /></span>
            </div>
          )}
          {entry?.evidenceUrl && (
            <div className="ach-report-row">
              <span className="k">{t('achievementModal.evidenceReportLabel')}</span>
              <span className="v"><a href={entry.evidenceUrl} target="_blank" rel="noopener noreferrer">{entry.evidenceUrl}</a></span>
            </div>
          )}
        </div>
      )}
    </Modal>
  )
}
