// Achievement add/edit modal, its read-only "report" counterpart, and the mutation hooks that
// power both -- shared between the Strategy Tree (StrategyTree.jsx) and the Annual Evaluation
// page (AnnualEvaluationPage.jsx), since achievements generated by a criterion-assigned
// achievement tool (e.g. Teaching Evaluations) have no measurement/Initiative at all and so can
// ONLY ever be edited/viewed from the Annual Evaluation page, never the Strategy Tree.
import { useEffect } from 'react'
import { Form, Input, Modal, Rate, Select, Alert, Typography, message } from 'antd'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import {
  getAchievements, getAchievementsAcrossYears, updateAchievement, deleteAchievement, getAchievementTypes,
} from '../api/strategies'
import {
  getMyCategories, getCategoriesForEmployee, getMyCycles, getCycleGoals,
  getEntryByAchievement, logAchievement as logAchievementWithEvaluation, upsertEntryForAchievement,
  getCriteria,
} from '../api/portfolio'
import { useAuth } from '../auth/AuthContext'

const { Text } = Typography

// AI-generated achievement details (e.g. the Teaching Evaluation tool's "Generated AI Review")
// come back as one long run-on string -- the model doesn't reliably emit a real newline after
// every "Section:" header or before every "*" bullet, so a plain pre-wrap won't fix it. Force a
// line break at those spots so the structure the prompt asked for actually reads as structure.
const AI_DETAILS_SECTION_HEADERS = [
  'Generated AI Review', 'Instructor Reflection', 'Course Information', 'Strengths', 'Areas for Improvement',
]

export function formatAiDetails(text) {
  if (!text) return text
  const headerPattern = new RegExp(`(${AI_DETAILS_SECTION_HEADERS.join('|')}):\\s*`, 'g')
  return text
    .replace(headerPattern, '$1:\n')
    .replace(/\s*\*\s+/g, '\n* ')
    .replace(/\n{3,}/g, '\n\n')
    .trim()
}

// ─── AchievementModal (add & edit) ───────────────────────────────────────────

export function AchievementModal({
  open, onClose, onSave, loading, initialValues, assessmentPeriods, academicYears = [], title, initialPeriodName,
  academicYearId, achievementId, authorId, moduleLocked,
}) {
  const [form] = Form.useForm()
  const { user } = useAuth()

  const { data: achievementTypes = [] } = useQuery({
    queryKey: ['achievement-types'],
    queryFn: getAchievementTypes,
    enabled: open,
  })

  // Editing someone else's achievement (Owner privilege) -- their categories/goals apply, not the editor's.
  const isSelf = !authorId || authorId === user?.userId

  const { data: categories = [], isError: categoriesError } = useQuery({
    queryKey: ['portfolio-categories-for-achievement', isSelf ? 'me' : authorId],
    queryFn: () => (isSelf ? getMyCategories() : getCategoriesForEmployee(authorId)),
    enabled: open,
    retry: false,
  })

  // The tree's own academic-year filter (`academicYearId`) is just a display filter and is often
  // unset -- it has nothing to do with which year this specific achievement belongs to. Resolve
  // the actual year from whichever assessment period the achievement is being recorded against
  // (periods and academic years share the same name, e.g. "2028-2029"), falling back to the tree
  // filter only if no period is known yet (the picker hasn't been touched).
  const watchedPeriodId = Form.useWatch('assessmentPeriodId', form)
  const selectedPeriodName = initialPeriodName ?? assessmentPeriods.find((p) => p.id === watchedPeriodId)?.name
  const effectiveAcademicYearId = selectedPeriodName
    ? academicYears.find((y) => y.name === selectedPeriodName)?.id
    : academicYearId

  const { data: myCycles = [] } = useQuery({
    queryKey: ['my-goal-cycles', effectiveAcademicYearId],
    queryFn: () => getMyCycles(effectiveAcademicYearId),
    enabled: open && isSelf && !!effectiveAcademicYearId,
  })
  const deployedCycle = myCycles.find((c) => c.state === 'DEPLOYED')
  const { data: myGoals = [] } = useQuery({
    queryKey: ['my-deployed-goals-for-achievement', deployedCycle?.id],
    queryFn: () => getCycleGoals(deployedCycle.id),
    enabled: open && isSelf && !!deployedCycle,
  })

  const { data: existingEntry } = useQuery({
    queryKey: ['portfolio-entry-for-achievement', achievementId],
    queryFn: () => getEntryByAchievement(achievementId),
    enabled: open && !!achievementId,
  })

  // Criteria narrows to whichever category is currently selected in the form -- reload as it changes.
  const selectedCategoryId = Form.useWatch('categoryId', form)
  const { data: criteria = [] } = useQuery({
    queryKey: ['portfolio-criteria-for-achievement', selectedCategoryId],
    queryFn: () => getCriteria(selectedCategoryId),
    enabled: open && !!selectedCategoryId,
  })

  // "Other" reveals a free-text field for a custom type -- matched by name since achievementTypeId
  // is whatever id the admin's AchievementType table happens to assign it.
  const selectedAchievementTypeId = Form.useWatch('achievementTypeId', form)
  const otherAchievementType = achievementTypes.find((t) => t.systemCode === 'OTHER')
  const isOtherType = !!otherAchievementType && selectedAchievementTypeId === otherAchievementType.id

  useEffect(() => {
    if (!open) return
    form.setFieldsValue({
      ...initialValues,
      categoryId: existingEntry?.categoryId,
      criteriaId: existingEntry?.criteriaId,
      categoryRating: existingEntry?.categoryRating,
      goalId: existingEntry?.goalId,
      evidenceUrl: existingEntry?.evidenceUrl,
    })
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [open, existingEntry])

  const handleOk = async () => {
    try {
      const values = await form.validateFields()
      onSave(values)
    } catch {}
  }

  const noCategoriesConfigured = open && (categoriesError || categories.length === 0)

  return (
    <Modal title={title} open={open} onCancel={onClose} onOk={handleOk}
      confirmLoading={loading} okButtonProps={{ disabled: noCategoriesConfigured }} destroyOnClose>
      <Form form={form} layout="vertical" initialValues={initialValues}>
        <Form.Item name="title" label="Title" rules={[{ required: true }]}>
          <Input />
        </Form.Item>
        <Form.Item name="achievementTypeId" label="Type" rules={[{ required: true }]}>
          <Select placeholder="Select type">
            {/* A deactivated type can't be picked for a new/different selection, but stays
                selectable here if it's the one this achievement already has -- so editing an old
                achievement never silently loses its type just because an admin retired it. */}
            {achievementTypes
              .filter((t) => t.active || t.id === selectedAchievementTypeId)
              .map((t) => (
                <Select.Option key={t.id} value={t.id}>{t.name}</Select.Option>
              ))}
          </Select>
        </Form.Item>
        {isOtherType && (
          <Form.Item name="customTypeName" label="Custom Type" rules={[{ required: true, message: 'Describe the achievement type' }]}>
            <Input placeholder="Describe the type of achievement" />
          </Form.Item>
        )}
        {/* Assessment period is always fixed by context, never freely editable here -- every
            achievement must belong to a period, and it can't be changed once set (see
            AchievementService.updateAchievement, which now ignores assessmentPeriodId entirely on
            update). Hidden field carries the ID through validateFields; a required rule guards
            against a caller forgetting to resolve one before opening this modal. */}
        <Form.Item name="assessmentPeriodId" hidden rules={[{ required: true, message: 'Assessment period is required' }]}>
          <Input />
        </Form.Item>
        <Form.Item label="Assessment Period">
          <span style={{
            display: 'inline-block', padding: '4px 10px', borderRadius: 6,
            background: '#eff6ff', color: '#1d4ed8', fontWeight: 600, fontSize: 13,
          }}>
            {initialPeriodName || '—'}
          </span>
        </Form.Item>
        <Form.Item name="details" label="Details"
          extra={moduleLocked ? 'Generated by the achievement-recording tool -- not editable' : undefined}>
          <Input.TextArea rows={2} disabled={moduleLocked} />
        </Form.Item>
        <Form.Item name="privateNotes" label="Private Notes" extra="Only visible to you">
          <Input.TextArea rows={2} />
        </Form.Item>

        {noCategoriesConfigured ? (
          <Alert type="warning" showIcon style={{ marginBottom: 16 }}
            message="Portfolio categories aren't configured yet"
            description="Ask an admin to configure portfolio categories for your title before recording achievements here." />
        ) : (
          <>
            <Form.Item name="categoryId" label="Evaluation Category" rules={[{ required: true }]}
              extra={moduleLocked
                ? 'Fixed by the achievement-recording tool that generated this achievement'
                : 'Which annual-portfolio category this achievement counts toward'}>
              <Select placeholder="Select category" disabled={moduleLocked}
                options={categories.map((c) => ({ value: c.id, label: c.categoryName }))}
                onChange={() => form.setFieldValue('criteriaId', undefined)} />
            </Form.Item>
            <Form.Item name="criteriaId" label="Criteria" rules={[{ required: true }]}
              extra="Which specific criteria within the category -- used later during the annual evaluation">
              <Select placeholder={selectedCategoryId ? 'Select criteria' : 'Select a category first'}
                disabled={!selectedCategoryId || moduleLocked}
                options={criteria.map((c) => ({ value: c.id, label: c.criteriaName }))} />
            </Form.Item>
          </>
        )}

        {isSelf && (
          <Form.Item name="goalId" label="Related Annual Goal (Optional)">
            <Select placeholder="Link to a deployed goal" allowClear
              options={myGoals.map((g) => ({ value: g.id, label: g.goalTitle }))} />
          </Form.Item>
        )}

        <Form.Item name="categoryRating" label="Self-Assessment Rating (Optional)">
          <Rate tooltips={['Poor', 'Fair', 'Good', 'Very Good', 'Excellent']} />
        </Form.Item>
        <Form.Item name="evidenceUrl" label="Evidence/Link" rules={[{ required: true, message: 'Evidence/Link is required' }]}
          extra="URL to evidence. Public link is prefered, but even a link to the evidence in your cloud storage open to public is fine">
          <Input placeholder="URL to certificate, publication, or evidence" />
        </Form.Item>
        {!isSelf && (
          <Text type="secondary" style={{ fontSize: 12 }}>
            Goal linking is only available to the achievement's author.
          </Text>
        )}
      </Form>
    </Modal>
  )
}

// ─── shared achievement mutations ────────────────────────────────────────────
// Recording an achievement is identical whether triggered from a period group inside
// AchievementsPanel, an Initiative card's own quick-add button, the rail's search-and-log picker,
// or the Annual Evaluation page's own Edit/Add -- one hook per action, every call site, no
// duplicated request-shaping/invalidation logic. `measurements`/`initiativeId`/`strategyId` are
// all optional -- achievements with no measurement (module-generated) simply skip those
// invalidations, since Strategy Tree queries can never be caching data for them anyway.

export function useAddAchievementMutation(measurements, initiativeId, strategyId, onSuccessExtra) {
  const qc = useQueryClient()
  return useMutation({
    mutationFn: (values) => logAchievementWithEvaluation({
      measurementId: measurements[0].id,
      achievementTitle: values.title,
      achievementTypeId: values.achievementTypeId,
      customTypeName: values.customTypeName,
      details: values.details,
      privateNotes: values.privateNotes,
      assessmentPeriodId: values.assessmentPeriodId,
      categoryId: values.categoryId,
      criteriaId: values.criteriaId,
      categoryRating: values.categoryRating,
      goalId: values.goalId,
      evidenceUrl: values.evidenceUrl,
    }),
    onSuccess: () => {
      message.success('Achievement recorded')
      ;(measurements ?? []).forEach((m) => qc.invalidateQueries({ queryKey: ['achievements', m.id] }))
      qc.invalidateQueries({ queryKey: ['achievements-across-years', initiativeId] })
      if (strategyId) qc.invalidateQueries({ queryKey: ['recent-achievements', strategyId] })
      onSuccessExtra?.()
    },
    onError: (err) => message.error(err.response?.data?.message || 'Failed to record achievement'),
  })
}

// Edit/delete are shared the same way -- used by AchievementsPanel's full list, the Initiative
// card's own quick-edit/delete icons, and the Annual Evaluation page's achievement column.
export function useEditAchievementMutation(measurements, initiativeId, strategyId, onSuccessExtra) {
  const qc = useQueryClient()
  return useMutation({
    mutationFn: async ({ achievementId, values }) => {
      await updateAchievement(achievementId, {
        title: values.title,
        achievementTypeId: values.achievementTypeId,
        customTypeName: values.customTypeName,
        details: values.details,
        privateNotes: values.privateNotes,
        assessmentPeriodId: values.assessmentPeriodId,
      })
      await upsertEntryForAchievement(achievementId, {
        categoryId: values.categoryId,
        criteriaId: values.criteriaId,
        categoryRating: values.categoryRating,
        goalId: values.goalId,
        evidenceUrl: values.evidenceUrl,
      })
    },
    onSuccess: () => {
      message.success('Achievement updated')
      ;(measurements ?? []).forEach((m) => qc.invalidateQueries({ queryKey: ['achievements', m.id] }))
      qc.invalidateQueries({ queryKey: ['achievements-across-years', initiativeId] })
      if (strategyId) qc.invalidateQueries({ queryKey: ['recent-achievements', strategyId] })
      onSuccessExtra?.()
    },
    onError: (err) => message.error(err.response?.data?.message || 'Update failed'),
  })
}

export function useDeleteAchievementMutation(measurements, initiativeId, strategyId, onSuccessExtra) {
  const qc = useQueryClient()
  return useMutation({
    mutationFn: (id) => deleteAchievement(id),
    onSuccess: () => {
      message.success('Achievement deleted')
      ;(measurements ?? []).forEach((m) => qc.invalidateQueries({ queryKey: ['achievements', m.id] }))
      qc.invalidateQueries({ queryKey: ['achievements-across-years', initiativeId] })
      if (strategyId) qc.invalidateQueries({ queryKey: ['recent-achievements', strategyId] })
      onSuccessExtra?.()
    },
    onError: (err) => message.error(err.response?.data?.message || 'Delete failed'),
  })
}

// ─── AchievementReportModal ───────────────────────────────────────────────────
// Read-only "report" view of one achievement, shaped by who's looking -- the backend has already
// done the actual redaction before this ever renders: `achievement.privateNotes` only arrives
// non-null when the viewer IS the author (see AchievementService.toResponse), and
// `entry.goalTitle`/`goalId` only arrive non-null when the viewer is the author OR the chair
// assigned to review them for that academic year (see PortfolioEntryService.canViewGoalLink) --
// everyone else sees the same "—" a genuinely goal-less achievement would show, which is also
// what keeps this safe to reuse verbatim from the Strategy Tree, the employee's own Annual
// Evaluation page, and the chair's Team Evaluations review.

export function AchievementReportModal({ achievement, onClose }) {
  const { data: entry, isLoading } = useQuery({
    queryKey: ['portfolio-entry-for-achievement', achievement?.id],
    queryFn: () => getEntryByAchievement(achievement.id),
    enabled: !!achievement,
  })

  return (
    <Modal title="Achievement Report" open={!!achievement} onCancel={onClose} footer={null} width={560} destroyOnClose>
      {!achievement ? null : isLoading ? (
        <div style={{ padding: 20, textAlign: 'center', color: '#9ca3af' }}>Loading…</div>
      ) : (
        <div className="ach-report">
          <div className="ach-report-row"><span className="k">Title</span><span className="v">{achievement.title}</span></div>
          <div className="ach-report-row"><span className="k">Type</span><span className="v">{achievement.customTypeName || achievement.achievementTypeName}</span></div>
          <div className="ach-report-row"><span className="k">Assessment Period</span><span className="v">{achievement.assessmentPeriodName || '—'}</span></div>
          <div className="ach-report-row"><span className="k">Recorded By</span><span className="v">{achievement.authorName}</span></div>
          <div className="ach-report-row"><span className="k">Recorded At</span><span className="v">{new Date(achievement.recordedAt).toLocaleString()}</span></div>
          <div className="ach-report-row"><span className="k">Details</span><span className="v" style={{ whiteSpace: 'pre-wrap' }}>{formatAiDetails(achievement.details) || '—'}</span></div>
          {/* Private Notes / Self-Assessment Rating / Evidence / Related Goal only ever arrive when
              the backend has decided this viewer is allowed to see them (see
              AchievementService.toResponse's isAuthor check and
              PortfolioEntryService.canViewSensitiveFields) -- for anyone else the row is hidden
              entirely, not shown blank, since a blank row reads as "empty" rather than "private". */}
          {achievement.privateNotes && (
            <div className="ach-report-row"><span className="k">Private Notes</span><span className="v">{achievement.privateNotes}</span></div>
          )}
          <div className="ach-report-row"><span className="k">Evaluation Category</span><span className="v">{entry?.categoryName || '—'}</span></div>
          <div className="ach-report-row"><span className="k">Criteria</span><span className="v">{entry?.criteriaName || '—'}</span></div>
          {entry?.goalTitle && (
            <div className="ach-report-row"><span className="k">Related Goal</span><span className="v">{entry.goalTitle}</span></div>
          )}
          {entry?.categoryRating && (
            <div className="ach-report-row">
              <span className="k">Self-Assessment Rating</span>
              <span className="v"><Rate disabled value={entry.categoryRating} style={{ fontSize: 14 }} /></span>
            </div>
          )}
          {entry?.evidenceUrl && (
            <div className="ach-report-row">
              <span className="k">Evidence</span>
              <span className="v"><a href={entry.evidenceUrl} target="_blank" rel="noopener noreferrer">{entry.evidenceUrl}</a></span>
            </div>
          )}
        </div>
      )}
    </Modal>
  )
}
